#!/bin/sh

N=1000
#z=4
iterations=10000

paramLow="0"
paramStep="0.1"
paramHigh="1"

replFraction="0.8"
initialCoop="0.5"

graphType=regular
gameType=SG

for z in 4 8 16 32
do
	echo "** z = $z"
	./generateData $graphType $N $z $replFraction $initialCoop $gameType $paramLow $paramStep $paramHigh $iterations
done
