#!/bin/sh

N=1000
#z=4
iterations=10000
runs=10

paramLow="0"
paramStep="0.1"
paramHigh="1"
initialCoop="0.5"

graphType=regular
gameType=SG

for z in 4 8 16 32
do
	echo "** z = $z"
	./generateData $graphType $N $z $initialCoop $gameType $paramLow $paramStep $paramHigh $iterations $runs
done
